#include <iostream>
/*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
            find the sum of the even-valued terms.

*/
int main() {
    std::cout << "Start" << std::endl;
    long fir = 2;
    long sec = 1;
    long long temp = 0;
    long long sum = 2;

    std::cout << "Start" << std::endl;
    while ((fir <= 4000000) && (sec <= 4000000)){
        temp = fir + sec;
        sec = fir;
        fir = temp;
        std::cout << "Term: "<< fir << std::endl;
        if(fir % 2 == 0){
            std::cout << "Even" << std::endl;
            sum += fir;
        }
    }
    std::cout << "Sum:" << sum << std::endl;
    
    return 0;
}